# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339d3894519b4dbeb4b070b3e8233aa6d20e647dba299586bace949905b5c4a4d7a62a0a9956e469caf8877de7bfd459988c073f3bb46f3b1792ed939f70c76b

test:
  secret_key_base: c46e8d96e43bc03f0499de8f8411ef39759621772deef994796b71bd281124ece44a4f4f7922c8817c019acb444eb42590bc9e3bb63da12161deb9d7ad7a074b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
